name: IWolfram (OSX)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [macOS]
        python-version: [3.6, 3.7, 3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew install llvm@9
        LLVM_CONFIG=/usr/local/Cellar/llvm@9/9.0.1_2/bin/llvm-config pip install llvmlite
        python -m pip install --upgrade pip
        python -m pip install wheel
        pip install -e git://github.com/mmatera/mathics#egg=Mathics3
        pip install ipywidgets
        pip install ipykernel
        pip install metakernel
        pip install jupyter_kernel_test
        pip install unittest2
        pip install -e git://github.com/Mathics3/pymathics-asy#egg=pymathics-asy
    - name: Install IWolfram
      run: |
        python -m pip install -e .
    - name: Test IWolfram
      run: |
        pip install pytest pexpect
        make -j3 check
